//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nedvig
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityModelContainer : DbContext
    {
        public EntityModelContainer()
            : base("name=EntityModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> AgentSet { get; set; }
        public virtual DbSet<Client> ClientSet { get; set; }
        public virtual DbSet<Need> NeedSet { get; set; }
        public virtual DbSet<ApartmentNeed> ApartmentNeedSet { get; set; }
        public virtual DbSet<LandNeed> LandNeedSet { get; set; }
        public virtual DbSet<HouseNeed> HouseNeedSet { get; set; }
        public virtual DbSet<Estate> EstateSet { get; set; }
        public virtual DbSet<Apartment> ApartmentSet { get; set; }
        public virtual DbSet<Land> LandSet { get; set; }
        public virtual DbSet<House> HouseSet { get; set; }
        public virtual DbSet<Offer> OfferSet { get; set; }
        public virtual DbSet<Deal> DealSet { get; set; }
    }
}
