//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nedvig
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseNeed
    {
        public int Id { get; set; }
        public Nullable<int> MaxRoom { get; set; }
        public Nullable<int> MinRoom { get; set; }
        public Nullable<int> MaxFloor { get; set; }
        public Nullable<int> MinFloor { get; set; }
        public Nullable<double> MaxArea { get; set; }
        public Nullable<double> MinArea { get; set; }
        public int IdNeed { get; set; }
    }
}
